@startuml
title Track Activity

Client -> TrackActivityAPI : { \n\t'text': 'I went to the gym for 2 hours yesterday evening'\n}
TrackActivityAPI -> Backend
Backend -> "Langchain Chain" : Invoke Chain
"Langchain Chain" --> LLMModel : Process Prompt
LLMModel -> "Langchain Chain" : Response
"Langchain Chain" -> ChatHistory : Save History
"Langchain Chain" --> OutputParser : Parse Output
OutputParser -> Backend : JSON Object
Backend -> TrackActivityAPI : Return Response
TrackActivityAPI -> Client : Send Response
@enduml

@startuml
title Activity Report

Client -> ActivityReportAPI : { \n\t'text': 'What all activities did I do last week?'\n}
ActivityReportAPI -> Backend
Backend -> "Langchain Chain" : Invoke Chain
"Langchain Chain" -> LLMModel : Process Prompt
LLMModel -> "Langchain Chain" : Response
"Langchain Chain" -> ChatHistory : Save History
"Langchain Chain" -> OutputParser : Parse Output
OutputParser -> Backend : JSON Object
Backend -> ActivityReportAPI : Return Response
ActivityReportAPI -> Client : Send Response
@enduml
